// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChtIJBpkAshVhDSdFrMaM8m5T8zeHk-2k',
    appId: '1:964923086673:web:a379af1e8ea471edf2e570',
    messagingSenderId: '964923086673',
    projectId: 'taxi-app-e1332',
    authDomain: 'taxi-app-e1332.firebaseapp.com',
    storageBucket: 'taxi-app-e1332.firebasestorage.app',
    measurementId: 'G-9GVP5LH92B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEyema21gaQP3OobIVijZrdmIzpl7hpeQ',
    appId: '1:964923086673:android:3ba03db6f0dd37bdf2e570',
    messagingSenderId: '964923086673',
    projectId: 'taxi-app-e1332',
    storageBucket: 'taxi-app-e1332.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn7JLqhmLyzRkdbqFE099CR57FDSAoOK0',
    appId: '1:964923086673:ios:129a22ff612afbbef2e570',
    messagingSenderId: '964923086673',
    projectId: 'taxi-app-e1332',
    storageBucket: 'taxi-app-e1332.firebasestorage.app',
    iosBundleId: 'com.taxi.taxiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn7JLqhmLyzRkdbqFE099CR57FDSAoOK0',
    appId: '1:964923086673:ios:8a6a1994793ead52f2e570',
    messagingSenderId: '964923086673',
    projectId: 'taxi-app-e1332',
    storageBucket: 'taxi-app-e1332.firebasestorage.app',
    iosBundleId: 'com.example.taxiAppInFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChtIJBpkAshVhDSdFrMaM8m5T8zeHk-2k',
    appId: '1:964923086673:web:2d187e43b74dc0d0f2e570',
    messagingSenderId: '964923086673',
    projectId: 'taxi-app-e1332',
    authDomain: 'taxi-app-e1332.firebaseapp.com',
    storageBucket: 'taxi-app-e1332.firebasestorage.app',
    measurementId: 'G-7YSE8K44G5',
  );
}
